=== szaboolevente/GF2465WebXMLLev/XMLTaskGF2465/XMLSchemaGF2465.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!-- Egyszerű típusok, saját típusok meghatározása -->
    <xs:element name="nev" type="xs:string" />
    <xs:element name="cim" type="xs:string" />
    <xs:element name="telefon" type="TelefonszámTípus" />
    <xs:element name="kor" type="xs:integer" />
    <xs:element name="szuletesi_datum" type="SzuletesiDatumTipus" />
    <xs:element name="fizetes" type="xs:integer" />
    <xs:element name="vezeteknev" type="xs:string" />
    <xs:element name="keresztnev" type="xs:string" />
    <xs:element name="rendszam" type="xs:string" />
    <xs:element name="tipus" type="xs:string" />
    <xs:element name="marka" type="xs:string" />
    <xs:element name="cserealkatresz" type="xs:string" />


    <xs:simpleType name="TelefonszámTípus">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}-\d{2}-\d{3}-\d{4}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="SzuletesiDatumTipus">
        <xs:restriction base="xs:date">
            <xs:minInclusive value="1900-01-01" />
            <xs:maxInclusive value="2005-12-31" />
        </xs:restriction>
    </xs:simpleType>

    <!-- Komplex típusok meghatározása -->
    <xs:complexType name="AutosiskolaTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string" />
            <xs:element name="cim" type="xs:string" />
            <xs:element ref="telefon" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="ai_id" type="xs:integer" />
    </xs:complexType>

    <xs:complexType name="UgyfelTipus">
        <xs:sequence>
            <xs:element name="nev">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="vezeteknev" />
                        <xs:element ref="keresztnev" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element ref="telefon" maxOccurs="unbounded" />
            <xs:element ref="kor" minOccurs="1" />
            <xs:element ref="szuletesi_datum" />
        </xs:sequence>
        <xs:attribute name="u_id" type="xs:integer" />
        <xs:attribute name="ai_id" type="xs:integer" />
        <xs:attribute name="o_id" type="xs:integer" />
    </xs:complexType>

    <xs:complexType name="OktatoTipus">
        <xs:sequence>
            <xs:element ref="nev" />
            <xs:element ref="fizetes" />
            <xs:element ref="telefon" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="o_id" type="xs:integer" />
        <xs:attribute name="ai_id" type="xs:integer" />
    </xs:complexType>

    <xs:complexType name="AutoTipus">
        <xs:sequence>
            <xs:element ref="rendszam" />
            <xs:element ref="tipus" />
            <xs:element ref="marka" />
        </xs:sequence>
        <xs:attribute name="au_id" type="xs:integer" />
        <xs:attribute name="o_id" type="xs:integer" />
    </xs:complexType>

    <xs:complexType name="SzereloTipus">
        <xs:sequence>
            <xs:element ref="nev" />
            <xs:element ref="fizetes" />
            <xs:element ref="telefon" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="sz_id" type="xs:integer" />
        <xs:attribute name="au_id" type="xs:integer" />
    </xs:complexType>

    <xs:complexType name="CserealkatreszTipus">
        <xs:sequence>
            <xs:element ref="cserealkatresz" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="au_id" type="xs:integer" />
        <xs:attribute name="sz_id" type="xs:integer" />
    </xs:complexType>

    <!-- Gyökér elem meghatározása -->
    <xs:element name="GF2465_Autosiskolak">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Autosiskola" type="AutosiskolaTipus" maxOccurs="unbounded" />
                <xs:element name="Ugyfel" type="UgyfelTipus" maxOccurs="unbounded" />
                <xs:element name="Oktato" type="OktatoTipus" maxOccurs="unbounded" />
                <xs:element name="Auto" type="AutoTipus" maxOccurs="unbounded" />
                <xs:element name="Szerelo" type="SzereloTipus" maxOccurs="unbounded" />
                <xs:element name="cserealkatreszek" type="CserealkatreszTipus" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>

        <!--Elsődleges
        kulcsok-->
        <xs:key name="AutosiskolaPK">
            <xs:selector xpath="Autosiskola" />
            <xs:field xpath="@ai_id" />
        </xs:key>

        <xs:key name="UgyfelPK">
            <xs:selector xpath="Ugyfel" />
            <xs:field xpath="@u_id" />
        </xs:key>

        <xs:key name="OktatoPK">
            <xs:selector xpath="Oktato" />
            <xs:field xpath="@o_id" />
        </xs:key>

        <xs:key name="AutoPK">
            <xs:selector xpath="Auto" />
            <xs:field xpath="@au_id" />
        </xs:key>

        <xs:key name="SzereloPK">
            <xs:selector xpath="Szerelo" />
            <xs:field xpath="@sz_id" />
        </xs:key>

        <!-- Idegen kulcsok -->
        <xs:keyref name="UgyfelAIFK" refer="AutosiskolaPK">
            <xs:selector xpath="Ugyfel" />
            <xs:field xpath="@ai_id" />
        </xs:keyref>

        <xs:keyref name="UgyfelOFK" refer="OktatoPK">
            <xs:selector xpath="Ugyfel" />
            <xs:field xpath="@o_id" />
        </xs:keyref>

        <xs:keyref name="OktatoFK" refer="AutosiskolaPK">
            <xs:selector xpath="Oktato" />
            <xs:field xpath="@ai_id" />
        </xs:keyref>

        <xs:keyref name="AutoFK" refer="OktatoPK">
            <xs:selector xpath="Auto" />
            <xs:field xpath="@o_id" />
        </xs:keyref>

        <xs:keyref name="SzereloFK" refer="AutoPK">
            <xs:selector xpath="Szerelo" />
            <xs:field xpath="@au_id" />
        </xs:keyref>

        <xs:keyref name="CserealkatreszAUFK" refer="AutoPK">
            <xs:selector xpath="Cserealkatresz" />
            <xs:field xpath="@au_id" />
        </xs:keyref>

        <xs:keyref name="CserealkatreszSFK" refer="SzereloPK">
            <xs:selector xpath="Cserealkatresz" />
            <xs:field xpath="@sz_id" />
        </xs:keyref>

        <!-- 1:1 -->
        <xs:unique name="Auto">
            <xs:selector xpath="Auto" />
            <xs:field xpath="@o_id" />
        </xs:unique>
    </xs:element>
</xs:schema>

=== szaboolevente/GF2465WebXMLLev/XMLTaskGF2465/DOMParseGF2465/src/XML_GF2465.xml
<?xml version="1.0" encoding="utf-8"?>
<GF2465_Autosiskolak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:noNamespaceSchemaLocation="XMLSchemaGF2465.xsd">

    <!-- Autosiskolák -->
    <Autosiskola ai_id="1">
        <nev>Go Car</nev>
        <cim>1111 Budapest, Kossuth Lajos utca 1.</cim>
        <telefon>06-70-123-4567</telefon>
        <telefon>06-30-123-4567</telefon>
    </Autosiskola>
    <Autosiskola ai_id="2">
        <nev>Guruljunk</nev>
        <cim>1111 Budapest, Petőfi utca 2.</cim>
        <telefon>06-70-123-4567</telefon>
    </Autosiskola>
    <Autosiskola ai_id="3">
        <nev>UNI</nev>
        <cim>3515, Miskolc, Egyetem út 1</cim>
        <telefon>06-70-123-4567</telefon>
        <telefon>06-30-123-4567</telefon>
    </Autosiskola>

    <!--Ügyfelek-->
    <Ugyfel u_id="1" ai_id="1" o_id="1">
        <nev>
            <vezeteknev>Nagy</vezeteknev>
            <keresztnev>Máté</keresztnev>
        </nev>
        <telefon>06-70-123-4567</telefon>
        <telefon>06-30-123-4567</telefon>
        <kor>18</kor>
        <szuletesi_datum>2003-01-01</szuletesi_datum>
    </Ugyfel>
    <Ugyfel u_id="2" ai_id="2" o_id="2">
        <nev>
            <vezeteknev>Gyáni</vezeteknev>
            <keresztnev>Kevin</keresztnev>
        </nev>
        <telefon>06-70-123-4567</telefon>
        <kor>18</kor>
        <szuletesi_datum>2003-01-01</szuletesi_datum>
    </Ugyfel>
    <Ugyfel u_id="3" ai_id="3" o_id="3">
        <nev>
            <vezeteknev>Kovács</vezeteknev>
            <keresztnev>Ádám</keresztnev>
        </nev>
        <telefon>06-70-123-4567</telefon>
        <telefon>06-30-123-4567</telefon>
        <kor>18</kor>
        <szuletesi_datum>2003-01-01</szuletesi_datum>
    </Ugyfel>

    <!-- Oktatók -->
    <Oktato o_id="1" ai_id="1">
        <nev>Kovács János</nev>
        <fizetes>300000</fizetes>
        <telefon>06-70-123-4567</telefon>
        <telefon>06-30-123-4567</telefon>
    </Oktato>
    <Oktato o_id="2" ai_id="2">
        <nev>Kiss János</nev>
        <fizetes>300000</fizetes>
        <telefon>06-70-123-4567</telefon>
    </Oktato>
    <Oktato o_id="3" ai_id="3">
        <nev>Nagy János</nev>
        <fizetes>300000</fizetes>
        <telefon>06-70-123-4567</telefon>
        <telefon>06-30-123-4567</telefon>
    </Oktato>

    <!-- Autók -->
    <Auto au_id="1" o_id="1">
        <rendszam>ABC-111</rendszam>
        <tipus>Astra</tipus>
        <marka>opel</marka>
    </Auto>
    <Auto au_id="2" o_id="2">
        <rendszam>ABC-222</rendszam>
        <tipus>Focus</tipus>
        <marka>Ford</marka>
    </Auto>
    <Auto au_id="3" o_id="3">
        <rendszam>ABC-333</rendszam>
        <tipus>Corolla</tipus>
        <marka>Toyota</marka>
    </Auto>

    <!-- Szerelők -->
    <Szerelo sz_id="1" au_id="1">
        <nev>Kovács Abdul</nev>
        <fizetes>400000</fizetes>
        <telefon>06-70-123-1111</telefon>
        <telefon>06-30-123-1112</telefon>
    </Szerelo>
    <Szerelo sz_id="2" au_id="2">
        <nev>Kiss Adorján</nev>
        <fizetes>420000</fizetes>
        <telefon>06-70-123-2222</telefon>
    </Szerelo>
    <Szerelo sz_id="3" au_id="3">
        <nev>Nagy Ferenc</nev>
        <fizetes>450000</fizetes>
        <telefon>06-70-123-3333</telefon>
        <telefon>06-30-123-3334</telefon>
    </Szerelo>

    <!-- Cserélt alkatrészek -->
    <cserealkatreszek au_id="1" sz_id="1">
        <cserealkatresz>fékbetét</cserealkatresz>
        <cserealkatresz>féktárcsa</cserealkatresz>
    </cserealkatreszek>
    <cserealkatreszek au_id="2" sz_id="2">
        <cserealkatresz>motor</cserealkatresz>
        <cserealkatresz>lengőkar</cserealkatresz>
    </cserealkatreszek>
    <cserealkatreszek au_id="3" sz_id="3">
        <cserealkatresz>szélvédő</cserealkatresz>
    </cserealkatreszek>

</GF2465_Autosiskolak>

=== szaboolevente/GF2465WebXMLLev/XMLTaskGF2465/DOMParseGF2465/XML_GF24651.xml
<?xml version="1.0" encoding="UTF-8"?>
<GF2465_Autosiskolak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaGF2465.xsd">
  <Autosiskola ai_id="1">
    <nev >Go Car</nev>
    <cim >1111 Budapest, Kossuth Lajos utca 1.</cim>
    <telefon >06-70-123-4567</telefon>
    <telefon >06-30-123-4567</telefon>
  </Autosiskola>

  <Autosiskola ai_id="2">
    <nev >Guruljunk</nev>
    <cim >1111 Budapest, Petőfi utca 2.</cim>
    <telefon >06-70-123-4567</telefon>
  </Autosiskola>

  <Autosiskola ai_id="3">
    <nev >UNI</nev>
    <cim >3515, Miskolc, Egyetem út 1</cim>
    <telefon >06-70-123-4567</telefon>
    <telefon >06-30-123-4567</telefon>
  </Autosiskola>


  <Ugyfel ai_id="1" o_id="1" u_id="1">
    <nev >
      <vezeteknev >Nagy</vezeteknev>
      <keresztnev >Máté</keresztnev>
    </nev>
    <telefon >06-70-123-4567</telefon>
    <telefon >06-30-123-4567</telefon>
    <kor >18</kor>
    <szuletesi_datum >2003-01-01</szuletesi_datum>
  </Ugyfel>

  <Ugyfel ai_id="2" o_id="2" u_id="2">
    <nev >
      <vezeteknev >Gyáni</vezeteknev>
      <keresztnev >Kevin</keresztnev>
    </nev>
    <telefon >06-70-123-4567</telefon>
    <kor >18</kor>
    <szuletesi_datum >2003-01-01</szuletesi_datum>
  </Ugyfel>

  <Ugyfel ai_id="3" o_id="3" u_id="3">
    <nev >
      <vezeteknev >Kovács</vezeteknev>
      <keresztnev >Ádám</keresztnev>
    </nev>
    <telefon >06-70-123-4567</telefon>
    <telefon >06-30-123-4567</telefon>
    <kor >18</kor>
    <szuletesi_datum >2003-01-01</szuletesi_datum>
  </Ugyfel>


  <Oktato ai_id="1" o_id="1">
    <nev >Kovács János</nev>
    <fizetes >300000</fizetes>
    <telefon >06-70-123-4567</telefon>
    <telefon >06-30-123-4567</telefon>
  </Oktato>

  <Oktato ai_id="2" o_id="2">
    <nev >Kiss János</nev>
    <fizetes >300000</fizetes>
    <telefon >06-70-123-4567</telefon>
  </Oktato>

  <Oktato ai_id="3" o_id="3">
    <nev >Nagy János</nev>
    <fizetes >300000</fizetes>
    <telefon >06-70-123-4567</telefon>
    <telefon >06-30-123-4567</telefon>
  </Oktato>


  <Auto au_id="1" o_id="1">
    <rendszam >ABC-111</rendszam>
    <tipus >Astra</tipus>
    <marka >opel</marka>
  </Auto>

  <Auto au_id="2" o_id="2">
    <rendszam >ABC-222</rendszam>
    <tipus >Focus</tipus>
    <marka >Ford</marka>
  </Auto>

  <Auto au_id="3" o_id="3">
    <rendszam >ABC-333</rendszam>
    <tipus >Corolla</tipus>
    <marka >Toyota</marka>
  </Auto>


  <Szerelo au_id="1" sz_id="1">
    <nev >Kovács Abdul</nev>
    <fizetes >400000</fizetes>
    <telefon >06-70-123-1111</telefon>
    <telefon >06-30-123-1112</telefon>
  </Szerelo>

  <Szerelo au_id="2" sz_id="2">
    <nev >Kiss Adorján</nev>
    <fizetes >420000</fizetes>
    <telefon >06-70-123-2222</telefon>
  </Szerelo>

  <Szerelo au_id="3" sz_id="3">
    <nev >Nagy Ferenc</nev>
    <fizetes >450000</fizetes>
    <telefon >06-70-123-3333</telefon>
    <telefon >06-30-123-3334</telefon>
  </Szerelo>


  <cserealkatreszek au_id="1" sz_id="1">
    <cserealkatresz >fékbetét</cserealkatresz>
    <cserealkatresz >féktárcsa</cserealkatresz>
  </cserealkatreszek>

  <cserealkatreszek au_id="2" sz_id="2">
    <cserealkatresz >motor</cserealkatresz>
    <cserealkatresz >lengőkar</cserealkatresz>
  </cserealkatreszek>

  <cserealkatreszek au_id="3" sz_id="3">
    <cserealkatresz >szélvédő</cserealkatresz>
  </cserealkatreszek>

</GF2465_Autosiskolak>
